syntax = "proto3";

package kenja_anime_search;

service AnimeSearch {
    rpc Search(Query) returns (stream Candidate);
}

enum Rating {
    RATING_UNSPECIFIED = 0;
    RATING_ALL_AGES = 1;
    RATING_HENTAI = 2;
}

message Query {
    string keyword = 1;
    Rating rating = 2;
}

enum DocumentType {
    DOCUMENT_TYPE_UNSPECIFIED = 0;
    DOCUMENT_TYPE_ANIME = 1;
    DOCUMENT_TYPE_CHARACTER = 2;
}

message ItemId {
    int64 id = 1;
    DocumentType document_type = 2;
}

message Parent {
    string name = 1;
    optional string name_japanese = 2;
}

message Candidate {
    ItemId id = 1; 
    optional Parent parent = 2;
    repeated string tags = 3;
    string name = 4;
    optional string name_english = 5;
    optional string name_japanese = 6;
}
